#!/usr/bin/env python3
"""
Import Canada coins Phase 2: 1858-1967 circulation coins
This script imports foundational Canadian circulation coins from Provincial era through silver era.
"""

import sqlite3
import json
from datetime import datetime
from pathlib import Path

def create_connection():
    """Create database connection."""
    db_path = Path(__file__).parent.parent / "coins.db"
    return sqlite3.connect(str(db_path))

def import_coins(conn):
    """Import Canada coins data."""
    cursor = conn.cursor()
    
    coins_data = [
        # Provincial Coins (1858)
        {
            'coin_id': 'CA-CENT-1858-RM',
            'year': 1858,
            'mint': 'RM',
            'denomination': '1 Cent',
            'series': 'Large Cent',
            'variety': None,
            'grade': None,
            'composition': '95% Cu, 5% Sn/Zn',
            'weight_grams': 4.54,
            'diameter_mm': 25.4,
            'thickness_mm': None,
            'edge': 'Plain',
            'designer': 'L.C. Wyon',
            'obverse_description': 'Young head Victoria left, VICTORIA DEI GRATIA REGINA',
            'reverse_description': 'ONE CENT 1858 within wreath',
            'business_strikes': 421000,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 421000,
            'notes': 'First Canadian cent, varieties include Coin alignment, Full vine, Broken stem',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-FIVE-1858-RM',
            'year': 1858,
            'mint': 'RM',
            'denomination': '5 Cents',
            'series': 'Provincial Silver',
            'variety': None,
            'grade': None,
            'composition': '92.5% Ag, 7.5% Cu',
            'weight_grams': 1.167,
            'diameter_mm': 15.5,
            'thickness_mm': None,
            'edge': 'Reeded',
            'designer': 'L.C. Wyon',
            'obverse_description': 'Young head Victoria left',
            'reverse_description': '5 CENTS 1858 within wreath',
            'business_strikes': 1460389,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 1460389,
            'notes': 'Small date and large date varieties',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-DIME-1858-RM',
            'year': 1858,
            'mint': 'RM',
            'denomination': '10 Cents',
            'series': 'Provincial Silver',
            'variety': None,
            'grade': None,
            'composition': '92.5% Ag, 7.5% Cu',
            'weight_grams': 2.324,
            'diameter_mm': 18.0,
            'thickness_mm': None,
            'edge': 'Reeded',
            'designer': 'L.C. Wyon',
            'obverse_description': 'Young head Victoria left',
            'reverse_description': '10 CENTS 1858 within wreath',
            'business_strikes': 1216402,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 1216402,
            'notes': 'First year of issue',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-TWTY-1858-RM',
            'year': 1858,
            'mint': 'RM',
            'denomination': '20 Cents',
            'series': 'Provincial Silver',
            'variety': None,
            'grade': None,
            'composition': '92.5% Ag, 7.5% Cu',
            'weight_grams': 4.648,
            'diameter_mm': 23.3,
            'thickness_mm': None,
            'edge': 'Reeded',
            'designer': 'L.C. Wyon',
            'obverse_description': 'Young head Victoria left',
            'reverse_description': '20 CENTS 1858 within wreath',
            'business_strikes': 730392,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 730392,
            'notes': 'Single year issue, replaced by 25 cents',
            'rarity': 'scarce',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        
        # Victoria Era (1870-1901) - Key dates
        {
            'coin_id': 'CA-CENT-1876-H',
            'year': 1876,
            'mint': 'H',
            'denomination': '1 Cent',
            'series': 'Large Cent',
            'variety': None,
            'grade': None,
            'composition': '95% Cu, 4% Sn, 1% Zn',
            'weight_grams': 5.67,
            'diameter_mm': 25.4,
            'thickness_mm': None,
            'edge': 'Plain',
            'designer': 'L.C. Wyon',
            'obverse_description': 'Laureate bust Victoria left',
            'reverse_description': 'ONE CENT date within wreath',
            'business_strikes': 4000000,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 4000000,
            'notes': 'H mint mark for Heaton Mint',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-FIVE-1870-RM',
            'year': 1870,
            'mint': 'RM',
            'denomination': '5 Cents',
            'series': 'Victoria Silver',
            'variety': None,
            'grade': None,
            'composition': '92.5% Ag, 7.5% Cu',
            'weight_grams': 1.167,
            'diameter_mm': 15.5,
            'thickness_mm': None,
            'edge': 'Reeded',
            'designer': 'L.C. Wyon',
            'obverse_description': 'Laureate bust Victoria left',
            'reverse_description': '5 CENTS date within wreath',
            'business_strikes': 2800000,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 2800000,
            'notes': 'Narrow rim and wide rim varieties',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-QRTR-1870-RM',
            'year': 1870,
            'mint': 'RM',
            'denomination': '25 Cents',
            'series': 'Victoria Silver',
            'variety': None,
            'grade': None,
            'composition': '92.5% Ag, 7.5% Cu',
            'weight_grams': 5.810,
            'diameter_mm': 23.88,
            'thickness_mm': None,
            'edge': 'Reeded',
            'designer': 'L.C. Wyon',
            'obverse_description': 'Laureate bust Victoria left',
            'reverse_description': '25 CENTS date within wreath',
            'business_strikes': 900000,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 900000,
            'notes': 'First year 25 cents replaced 20 cents',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        
        # Edward VII Era (1902-1910)
        {
            'coin_id': 'CA-CENT-1902-RM',
            'year': 1902,
            'mint': 'RM',
            'denomination': '1 Cent',
            'series': 'Large Cent',
            'variety': None,
            'grade': None,
            'composition': '95% Cu, 4% Sn, 1% Zn',
            'weight_grams': 5.67,
            'diameter_mm': 25.4,
            'thickness_mm': None,
            'edge': 'Plain',
            'designer': 'G.W. DeSaulles',
            'obverse_description': 'Crowned bust Edward VII right',
            'reverse_description': 'ONE CENT date within wreath',
            'business_strikes': 3000000,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 3000000,
            'notes': 'First year of Edward VII',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        
        # George V Era (1911-1936) - Including key dates
        {
            'coin_id': 'CA-CENT-1920-RM',
            'year': 1920,
            'mint': 'RM',
            'denomination': '1 Cent',
            'series': 'Small Cent',
            'variety': None,
            'grade': None,
            'composition': '95.5% Cu, 3% Sn, 1.5% Zn',
            'weight_grams': 3.24,
            'diameter_mm': 19.05,
            'thickness_mm': None,
            'edge': 'Plain',
            'designer': 'Sir E.B. MacKennal',
            'obverse_description': 'Crowned bust George V left',
            'reverse_description': 'ONE CENT date, maple leaves',
            'business_strikes': 6762247,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 6762247,
            'notes': 'First year small cent',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-CENT-1923-RM',
            'year': 1923,
            'mint': 'RM',
            'denomination': '1 Cent',
            'series': 'Small Cent',
            'variety': None,
            'grade': None,
            'composition': '95.5% Cu, 3% Sn, 1.5% Zn',
            'weight_grams': 3.24,
            'diameter_mm': 19.05,
            'thickness_mm': None,
            'edge': 'Plain',
            'designer': 'Sir E.B. MacKennal',
            'obverse_description': 'Crowned bust George V left',
            'reverse_description': 'ONE CENT date, maple leaves',
            'business_strikes': 1019002,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 1019002,
            'notes': 'Key date, low mintage',
            'rarity': 'key',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-FIVE-1921-RM',
            'year': 1921,
            'mint': 'RM',
            'denomination': '5 Cents',
            'series': 'George V Silver',
            'variety': None,
            'grade': None,
            'composition': '80% Ag, 20% Cu',
            'weight_grams': 1.167,
            'diameter_mm': 15.5,
            'thickness_mm': None,
            'edge': 'Reeded',
            'designer': 'Sir E.B. MacKennal',
            'obverse_description': 'Crowned bust George V left',
            'reverse_description': '5 CENTS date within wreath',
            'business_strikes': 2582495,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 2582495,
            'notes': 'Prince of Canadian coins, most melted, <400 survive',
            'rarity': 'key',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-HALF-1921-RM',
            'year': 1921,
            'mint': 'RM',
            'denomination': '50 Cents',
            'series': 'George V Silver',
            'variety': None,
            'grade': None,
            'composition': '80% Ag, 20% Cu',
            'weight_grams': 11.66,
            'diameter_mm': 29.72,
            'thickness_mm': None,
            'edge': 'Reeded',
            'designer': 'Sir E.B. MacKennal',
            'obverse_description': 'Crowned bust George V left',
            'reverse_description': 'Coat of arms, 50 CENTS date',
            'business_strikes': 206398,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 206398,
            'notes': 'King of Canadian coins, most melted, <75 survive',
            'rarity': 'key',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-CENT-1936-RM',
            'year': 1936,
            'mint': 'RM',
            'denomination': '1 Cent',
            'series': 'Small Cent',
            'variety': 'Dot',
            'grade': None,
            'composition': '95.5% Cu, 3% Sn, 1.5% Zn',
            'weight_grams': 3.24,
            'diameter_mm': 19.05,
            'thickness_mm': None,
            'edge': 'Plain',
            'designer': 'Sir E.B. MacKennal',
            'obverse_description': 'Crowned bust George V left',
            'reverse_description': 'ONE CENT date with dot below, maple leaves',
            'business_strikes': 678823,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 678823,
            'notes': 'Dot variety, emergency issue after George V death',
            'rarity': 'key',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        
        # George VI Era (1937-1952)
        {
            'coin_id': 'CA-CENT-1937-RM',
            'year': 1937,
            'mint': 'RM',
            'denomination': '1 Cent',
            'series': 'Small Cent',
            'variety': None,
            'grade': None,
            'composition': '95.5% Cu, 3% Sn, 1.5% Zn',
            'weight_grams': 3.24,
            'diameter_mm': 19.05,
            'thickness_mm': None,
            'edge': 'Plain',
            'designer': 'T.H. Paget',
            'obverse_description': 'Uncrowned head George VI left',
            'reverse_description': 'Maple twig design',
            'business_strikes': 10040231,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 10040231,
            'notes': 'First year George VI, new reverse design',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-FIVE-1937-RM',
            'year': 1937,
            'mint': 'RM',
            'denomination': '5 Cents',
            'series': 'George VI Nickel',
            'variety': None,
            'grade': None,
            'composition': '99.9% Ni',
            'weight_grams': 4.54,
            'diameter_mm': 21.21,
            'thickness_mm': None,
            'edge': 'Plain',
            'designer': 'T.H. Paget / G.E. Kruger-Gray',
            'obverse_description': 'Uncrowned head George VI left',
            'reverse_description': 'Beaver on rock, new iconic design',
            'business_strikes': 4593263,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 4593263,
            'notes': 'First year beaver design',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-DIME-1937-RM',
            'year': 1937,
            'mint': 'RM',
            'denomination': '10 Cents',
            'series': 'George VI Silver',
            'variety': None,
            'grade': None,
            'composition': '80% Ag, 20% Cu',
            'weight_grams': 2.33,
            'diameter_mm': 18.03,
            'thickness_mm': None,
            'edge': 'Reeded',
            'designer': 'T.H. Paget / Emanuel Hahn',
            'obverse_description': 'Uncrowned head George VI left',
            'reverse_description': 'Bluenose schooner sailing left',
            'business_strikes': 2500095,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 2500095,
            'notes': 'First year Bluenose design',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-QRTR-1937-RM',
            'year': 1937,
            'mint': 'RM',
            'denomination': '25 Cents',
            'series': 'George VI Silver',
            'variety': None,
            'grade': None,
            'composition': '80% Ag, 20% Cu',
            'weight_grams': 5.83,
            'diameter_mm': 23.88,
            'thickness_mm': None,
            'edge': 'Reeded',
            'designer': 'T.H. Paget / Emanuel Hahn',
            'obverse_description': 'Uncrowned head George VI left',
            'reverse_description': 'Caribou head left',
            'business_strikes': 2690176,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 2690176,
            'notes': 'First year caribou design',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-FIVE-1942-RM',
            'year': 1942,
            'mint': 'RM',
            'denomination': '5 Cents',
            'series': 'George VI Tombac',
            'variety': None,
            'grade': None,
            'composition': '88% Cu, 12% Zn',
            'weight_grams': 4.54,
            'diameter_mm': 21.21,
            'thickness_mm': None,
            'edge': 'Plain',
            'designer': 'T.H. Paget / Thomas Shingles',
            'obverse_description': 'Uncrowned head George VI left',
            'reverse_description': 'V for Victory torch design',
            'business_strikes': 3396234,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 3396234,
            'notes': 'WWII tombac brass composition',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-FIVE-1944-RM',
            'year': 1944,
            'mint': 'RM',
            'denomination': '5 Cents',
            'series': 'George VI Steel',
            'variety': None,
            'grade': None,
            'composition': 'Chromium-plated steel',
            'weight_grams': 4.54,
            'diameter_mm': 21.21,
            'thickness_mm': None,
            'edge': 'Plain',
            'designer': 'T.H. Paget / Thomas Shingles',
            'obverse_description': 'Uncrowned head George VI left',
            'reverse_description': 'V for Victory torch design',
            'business_strikes': 11532784,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 11532784,
            'notes': 'WWII chromium-plated steel',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-DLLS-1947-RM',
            'year': 1947,
            'mint': 'RM',
            'denomination': '1 Dollar',
            'series': 'George VI Silver Dollar',
            'variety': 'Maple Leaf',
            'grade': None,
            'composition': '80% Ag, 20% Cu',
            'weight_grams': 23.33,
            'diameter_mm': 36.0,
            'thickness_mm': None,
            'edge': 'Reeded',
            'designer': 'T.H. Paget / Emanuel Hahn',
            'obverse_description': 'Uncrowned head George VI left',
            'reverse_description': 'Voyageur and Indian in canoe, maple leaf privy mark',
            'business_strikes': 21135,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 21135,
            'notes': 'Maple Leaf variety struck in 1948',
            'rarity': 'scarce',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        
        # Elizabeth II Early Era (1953-1967)
        {
            'coin_id': 'CA-CENT-1953-RM',
            'year': 1953,
            'mint': 'RM',
            'denomination': '1 Cent',
            'series': 'Small Cent',
            'variety': None,
            'grade': None,
            'composition': '98% Cu, 0.5% Sn, 1.5% Zn',
            'weight_grams': 3.24,
            'diameter_mm': 19.05,
            'thickness_mm': None,
            'edge': 'Plain',
            'designer': 'Mary Gillick',
            'obverse_description': 'Laureate bust Elizabeth II right',
            'reverse_description': 'Maple twig design',
            'business_strikes': 67806016,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 67806016,
            'notes': 'First year Elizabeth II',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-QRTR-1967-RM',
            'year': 1967,
            'mint': 'RM',
            'denomination': '25 Cents',
            'series': 'Centennial',
            'variety': None,
            'grade': None,
            'composition': '80% Ag, 20% Cu',
            'weight_grams': 5.83,
            'diameter_mm': 23.88,
            'thickness_mm': None,
            'edge': 'Reeded',
            'designer': 'Arnold Machin / Alex Colville',
            'obverse_description': 'Tiara bust Elizabeth II right',
            'reverse_description': 'Bobcat',
            'business_strikes': 48855500,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 48855500,
            'notes': 'Centennial commemorative with bobcat',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-DLLS-1967-RM',
            'year': 1967,
            'mint': 'RM',
            'denomination': '1 Dollar',
            'series': 'Centennial',
            'variety': None,
            'grade': None,
            'composition': '80% Ag, 20% Cu',
            'weight_grams': 23.33,
            'diameter_mm': 36.0,
            'thickness_mm': None,
            'edge': 'Reeded',
            'designer': 'Arnold Machin / Raymond Taylor',
            'obverse_description': 'Tiara bust Elizabeth II right',
            'reverse_description': 'Canada goose in flight',
            'business_strikes': 6767496,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 6767496,
            'notes': 'Centennial commemorative, last circulating silver dollar',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        
        # Dollar Coins (1935-1967) - Additional key dates
        {
            'coin_id': 'CA-DLLS-1935-RM',
            'year': 1935,
            'mint': 'RM',
            'denomination': '1 Dollar',
            'series': 'George V Silver Dollar',
            'variety': None,
            'grade': None,
            'composition': '80% Ag, 20% Cu',
            'weight_grams': 23.33,
            'diameter_mm': 36.0,
            'thickness_mm': None,
            'edge': 'Reeded',
            'designer': 'Sir E.B. MacKennal / Emanuel Hahn',
            'obverse_description': 'Crowned bust George V left',
            'reverse_description': 'Voyageur and Indian in canoe',
            'business_strikes': 428707,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 428707,
            'notes': 'First Canadian silver dollar, Silver Jubilee commemorative',
            'rarity': 'common',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        },
        {
            'coin_id': 'CA-DLLS-1948-RM',
            'year': 1948,
            'mint': 'RM',
            'denomination': '1 Dollar',
            'series': 'George VI Silver Dollar',
            'variety': None,
            'grade': None,
            'composition': '80% Ag, 20% Cu',
            'weight_grams': 23.33,
            'diameter_mm': 36.0,
            'thickness_mm': None,
            'edge': 'Reeded',
            'designer': 'T.H. Paget / Emanuel Hahn',
            'obverse_description': 'Uncrowned head George VI left',
            'reverse_description': 'Voyageur and Indian in canoe',
            'business_strikes': 18780,
            'proof_strikes': None,
            'uncirculated_strikes': None,
            'mint_state_strikes': None,
            'special_strikes': None,
            'total_mintage': 18780,
            'notes': 'Lowest mintage Canadian silver dollar',
            'rarity': 'key',
            'source_citation': 'Charlton Standard Catalogue of Canadian Coins'
        }
    ]
    
    # Insert coins
    insert_query = '''
        INSERT OR REPLACE INTO coins (
            coin_id, year, mint, denomination, series, variety, grade,
            composition, weight_grams, diameter_mm, thickness_mm, edge,
            designer, obverse_description, reverse_description,
            business_strikes, proof_strikes, uncirculated_strikes,
            mint_state_strikes, special_strikes, total_mintage,
            notes, rarity, source_citation
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    '''
    
    for coin in coins_data:
        cursor.execute(insert_query, (
            coin['coin_id'], coin['year'], coin['mint'], coin['denomination'],
            coin['series'], coin['variety'], coin['grade'], coin['composition'],
            coin['weight_grams'], coin['diameter_mm'], coin['thickness_mm'],
            coin['edge'], coin['designer'], coin['obverse_description'],
            coin['reverse_description'], coin['business_strikes'],
            coin['proof_strikes'], coin['uncirculated_strikes'],
            coin['mint_state_strikes'], coin['special_strikes'],
            coin['total_mintage'], coin['notes'], coin['rarity'],
            coin['source_citation']
        ))
    
    conn.commit()
    print(f"✅ Imported {len(coins_data)} Canada coins (1858-1967)")
    
    # Print summary
    cursor.execute('''
        SELECT denomination, COUNT(*) as count
        FROM coins
        WHERE coin_id LIKE 'CA-%'
        GROUP BY denomination
        ORDER BY denomination
    ''')
    
    print("\n📊 Canada coins by denomination:")
    for row in cursor.fetchall():
        print(f"  {row[0]}: {row[1]} coins")
    
    cursor.execute('''
        SELECT MIN(year), MAX(year), COUNT(DISTINCT year)
        FROM coins
        WHERE coin_id LIKE 'CA-%'
    ''')
    
    min_year, max_year, year_count = cursor.fetchone()
    print(f"\n📅 Year range: {min_year}-{max_year} ({year_count} distinct years)")
    
    cursor.execute('''
        SELECT COUNT(*)
        FROM coins
        WHERE coin_id LIKE 'CA-%' AND rarity = 'key'
    ''')
    
    key_count = cursor.fetchone()[0]
    print(f"\n🔑 Key dates: {key_count} coins")

def main():
    """Main function."""
    print("🇨🇦 Canada Coins Phase 2 Import - 1858-1967 Circulation Coins")
    print("=" * 60)
    
    conn = create_connection()
    try:
        import_coins(conn)
        print("\n✅ Phase 2 import completed successfully!")
    finally:
        conn.close()

if __name__ == "__main__":
    main()